# Generated by Django 4.1.2 on 2022-10-16 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=35, unique=True, verbose_name='Login')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания акаунта')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('descriphons', models.CharField(max_length=2000, verbose_name='Описание')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания акаунта')),
                ('post_url', models.URLField(max_length=255)),
                ('user_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum_app.user')),
            ],
        ),
    ]
