# Generated by Django 4.1.2 on 2022-10-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('login', models.CharField(max_length=35, unique=True, verbose_name='Login')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('create_date', models.DateTimeField(verbose_name='Дата создания акаунта')),
            ],
        ),
    ]
